[default]
timeout = 300

[heartnn]
title = "heartnn的自留地"
url = "https://www.heartnn.com/"
entrySelector = "article.post"
titleSelector = "h2.post-title > a"
linkSelector = "h2.post-title > a"


[akarat]
title = "Tristram"
url = "https://akarat.xyz/"
entrySelector = "li.post-item"
titleSelector = "> span > a"
linkSelector = "> span > a"
dateSelector = "time.datePublished"
dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"

[bestcherish]
title = "灰常记忆"
url = "https://bestcherish.com/"
entrySelector = "header.entry-header"
titleSelector = "h1.entry-title > a"
linkSelector = "a"

[kisnows]
title = "抹桥的博客"
url = "https://blog.kisnows.com/"
entrySelector = "article.post-block"
titleSelector = "a.post-title-link"
linkSelector = "a.post-title-link"
