[default]
timeout = 300

[heartnn]
title = "heartnn的自留地"
url = "https://www.heartnn.com/"
entrySelector = "article.post"
titleSelector = "h2.post-title > a"
linkSelector = "h2.post-title > a"


[akarat]
title = "Tristram"
url = "https://akarat.xyz/"
entrySelector = "li.post-item"
titleSelector = "> span > a"
linkSelector = "> span > a"
dateSelector = "time.datePublished"
dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"

[neugierig]
title = "neugierig"
url = "http://neugierig.org/software/blog/"
entrySelector = "tr.summary"
titleSelector = "h2"
linkSelector = "a.hiddenlink"
contentSelector = "a.hiddenlink div"
dateSelector = "td.date"
dateFormat = "y/M/d"
