[default]
timeout = 1200


[heartnn]
title = "heartnn的自留地"
url = "https://www.heartnn.com/archives/"
entrySelector = "section > div > ul > li"
titleSelector = "> a"
linkSelector = "> a"


[akarat]
title = "Tristram"
url = "https://akarat.xyz/"
entrySelector = "li.post-item"
titleSelector = "> span > a"
linkSelector = "> span > a"
dateSelector = "time.datePublished"
dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"

[bestcherish]
title = "灰常记忆"
url = "https://bestcherish.com/archive"
entrySelector = "div.sya_postcontent"
titleSelector = "a.sya_postlink"
linkSelector = "a.sya_postlink"

[kisnows]
title = "抹桥的博客"
url = "https://blog.kisnows.com/archives/"
entrySelector = "header.post-header"
titleSelector = "a.post-title-link > span"
linkSelector = "a.post-title-link > span"

[shuxiao]
title = "流水沉微"
url = "https://shuxiao.wang/posts/"
entrySelector = "div.post-item"
titleSelector = "div"
linkSelector = "a"


[yinwang]
title = "当然我在扯淡"
url = "https://www.yinwang.org/"
entrySelector = "li.list-group-item"
titleSelector = "> a"
linkSelector = "a"

[chinese-future]
title = "中国:历史与未来"
url = "https://www.chinese-future.org/"
entrySelector = "div.summary-item"
titleSelector = "a.summary-title-link"
linkSelector = "a.summary-title-link"
