[default]
timeout = 30

[heartnn]
title = "heartnn的自留地"
url = "https://www.heartnn.com/"
entrySelector = "article.post"
titleSelector = "h2.post-title > a"
linkSelector = "h2.post-title > a"


[akarat]
title = "Tristram"
url = "https://akarat.xyz/"
entrySelector = "li.post-item"
titleSelector = "> span > a"
linkSelector = "> span > a"
